# Generated by Django 5.1.2 on 2024-11-14 18:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(default='domyślny tekst'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='domyślny tekst'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='domyślny tytuł', max_length=100),
        ),
    ]
