# Generated by Django 5.1.2 on 2024-11-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_technology_project_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='domyślny tytuł', max_length=200),
        ),
    ]
